const {
  dateConversion,
  getFirstItemInArray,
  getImgUrl,
  getSecondItemInArray,
  nameCheck,
  removeDoubleSpace,
  removeNewLines,
  removeParams,
  reverseNameOrder,
  splitBySemiColon,
  stripMarkUp,
  toIso,
} = require("./util");

module.exports.source = {
  british_journal_for_the_history_of_philosophy: {
    name: "British Journal for the History of Philosophy",
    color: "12",
    filter: true,
    rssOnly: false,
    url: "https://www.tandfonline.com/feed/rss/rbjh20",

    metadataConfig: {
      abstract: { property: ["openGraph", "description"], do: false },
      author: { property: ["dublinCore", "creator"], do: removeDoubleSpace },
      date: { property: ["dublinCore", "date"], do: dateConversion },
      doi: { property: ["dublinCore", "identifier"], do: getFirstItemInArray },
      title: { property: ["dublinCore", "title"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
      keywords: { property: ["dublinCore", "subject"], do: splitBySemiColon },
      url: { property: ["openGraph", "url"], do: false },
    },
  },
  british_journal_for_the_philosophy_of_science: {
    name: "British Journal for the Philosophy of Science",
    url: "https://academic.oup.com/rss/site_5434/3295.xml",
    color: "8",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      firstpage: { property: "prism:startingPage", do: false },
      issue: { property: "prism:number", do: false },
      lastpage: { property: "prism:endingPage", do: false },
      title: { property: "title", do: false },
      url: { property: "link", do: removeParams },
      volume: { property: "prism:volume", do: false },
    },

    metadataConfig: {
      abstract: { property: ["general", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: reverseNameOrder },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      institution: {
        property: ["highwirePress", "author_institution"],
        do: "arr?",
      },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["general", "canonical"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
    },
  },
  kant_studien: {
    name: "Kant Studien",
    url:
      "https://www.degruyter.com/journalissuetocrss/journals/kant/kant-overview.xml",
    color: "15",
    rss: "custom",
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: false },
      date: { property: "isoDate", do: false },
      title: { property: "title", do: false },
      url: { property: "link", do: false },
    },

    metadataConfig: {
      abstract: { property: ["openGraph", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: nameCheck },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      keywords: { property: ["openGraph", "tag"], do: false },
      title: { property: ["openGraph", "title"], do: false },
      url: { property: ["general", "canonical"], do: removeParams },
      volume: { property: ["highwirePress", "volume"], do: false },
    },
  },
  kantian_review: {
    name: "Kantian Review",
    url:
      "https://www.cambridge.org/core/rss/product/id/D3E55E88C6269FFD657D4E68B193ADAB",
    color: "16",
    filter: false,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content", do: false },
      author: { property: "creator", do: false },
      date: { property: "dc:date", do: toIso },
      title: { property: "title", do: false },
      url: { property: "link", do: removeParams },
    },

    metadataConfig: {
      abstract: { property: ["highwirePress", "abstract"], do: stripMarkUp },
      author: { property: ["highwirePress", "author"], do: false },
      date: { property: ["highwirePress", "online_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      keywords: {
        property: ["highwirePress", "keywords"],
        do: splitBySemiColon,
      },
      title: { property: ["highwirePress", "title"], do: false },
      url: { property: ["general", "canonical"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
    },
  },
  european_journal_of_philosophy: {
    name: "European Journal of Philosophy",
    url: "https://onlinelibrary.wiley.com/feed/14680378/most-recent",
    color: "14",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "date", do: false },
      title: { property: "title", do: false },
      url: { property: "link", do: removeParams },
    },

    metadataConfig: {
      abstract: { property: ["openGraph", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: false },
      date: { property: ["highwirePress", "online_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      title: { property: ["openGraph", "title"], do: false },
      url: { property: ["openGraph", "url"], do: false },
    },
  },
  canadian_journal_of_philosophy: {
    name: "Canadian Journal of Philosophy",
    url: "https://www.tandfonline.com/feed/rss/rcjp20",
    color: "13",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "description", do: false },
      author: { property: "dc:creator", do: false },
      date: { property: "prism:coverDate", do: false },
      doi: { property: "dc:identifier", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },

    metadataConfig: {
      abstract: { property: ["dublinCore", "description"], do: false },
      author: { property: ["dublinCore", "creator"], do: false },
      date: { property: ["dublinCore", "date"], do: dateConversion },
      doi: { property: ["dublinCore", "source"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      title: { property: ["openGraph", "title"], do: false },
      url: { property: ["openGraph", "url"], do: false },
    },
  },
  graduate_faculty_philosophy_journal: {
    name: "Graduate Faculty Philosophy Journal",
    url: "https://www.pdcnet.org/pdc/bvdb.nsf/getrssxml?openagent&synonym=gfpj",
    color: "11",
    filter: true,
    rssOnly: true,

    rssConfig: {
      abstract: { property: "contentSnippet", do: false },
      author: { property: "creator", do: false },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: null },
    },
  },
  nous: {
    name: "Noûs",
    url: "https://onlinelibrary.wiley.com/feed/14680068/most-recent",
    color: "10",
    filter: true,
    rssOnly: true,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },
    metadataConfig: {
      abstract: { property: ["openGraph", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: false },
      date: { property: ["highwirePress", "online_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
      institution: {
        property: ["highwirePress", "author_institution"],
        do: false,
      },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      title: { property: ["openGraph", "title"], do: false },
      url: { property: ["openGraph", "url"], do: false },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
    },
  },
  ethics: {
    name: "Ethics",
    url:
      "https://www.journals.uchicago.edu/action/showFeed?type=etoc&feed=rss&jc=et",
    color: "9",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },

    metadataConfig: {
      abstract: { property: ["dublinCore", "description"], do: false },
      author: { property: ["dublinCore", "creator"], do: removeDoubleSpace },
      date: { property: ["dublinCore", "date"], do: toIso },
      doi: { property: ["dublinCore", "identifier"], do: getFirstItemInArray },

      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      title: { property: ["dublinCore", "title"], do: false },
      url: { property: ["dublinCore", "source"], do: false },
    },
  },
  idealistic_studies: {
    name: "Idealistic Studies",
    url:
      "https://www.pdcnet.org/pdc/bvdb.nsf/getrssxml?openagent&synonym=idstudies",
    color: "7",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },

    metadataConfig: {
      abstract: { property: ["general", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: reverseNameOrder },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      institution: {
        property: ["highwirePress", "author_institution"],
        do: false,
      },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["general", "canonical"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
    },
  },
  inquiry: {
    name: "Inquiry",
    url: "https://www.tandfonline.com/feed/rss/sinq20",
    color: "6",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },

    metadataConfig: {
      abstract: { property: ["dublinCore", "description"], do: false },
      author: {
        property: ["dublinCore", "creator"],
        do: removeDoubleSpace,
      },
      date: { property: ["dublinCore", "date"], do: dateConversion },
      doi: { property: ["dublinCore", "identifier"], do: getSecondItemInArray },
      image: { property: ["openGraph", "image"], do: getImgUrl },
      keywords: { property: ["dublinCore", "subject"], do: splitBySemiColon },
      title: { property: ["openGraph", "title"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["openGraph", "url"], do: false },
    },
  },
  the_philosophical_inquiry: {
    name: "The Philosophical Inquiry",
    url: "https://academic.oup.com/rss/site_5498/3359.xml",
    color: "5",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },
    metadataConfig: {
      abstract: { property: ["openGraph", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: reverseNameOrder },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      institution: {
        property: ["highwirePress", "author_institution"],
        do: false,
      },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      image: { property: ["openGraph", "image"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["general", "canonical"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
      keywords: { property: ["jsonLd", "keywords"], do: false },
    },
  },
  philosophy_and_phenomenological_research: {
    name: "Philosophy and Phenomenological Research",
    url: "https://onlinelibrary.wiley.com/feed/19331592/most-recent",
    color: "4",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },
    metadataConfig: {
      abstract: { property: ["general", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: reverseNameOrder },
      date: { property: ["highwirePress", "online_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      institution: {
        property: ["highwirePress", "author_institution"],
        do: "arr?",
      },
      title: { property: ["highwirePress", "title"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["openGraph", "url"], do: false },
      keywords: { property: ["highwirePress", "keywords"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
    },
  },
  the_monist: {
    name: "The Monist",
    url: "http://academic.oup.com/rss/site_5491/3352.xml",
    color: "3",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },
    metadataConfig: {
      abstract: { property: ["general", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: reverseNameOrder },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      institution: {
        property: ["highwirePress", "author_institution"],
        do: "arr?",
      },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["general", "canonical"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
    },
  },
  philosophical_topics: {
    name: "Philosophical Topics",
    url:
      "https://www.pdcnet.org/pdc/bvdb.nsf/getrssxml?openagent&synonym=philtopics",
    color: "2",
    filter: true,
    rssOnly: true,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },
    metadataConfig: {
      abstract: { property: ["general", "description"], do: false },
      author: { property: ["highwirePress", "author"], do: reverseNameOrder },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      institution: {
        property: ["highwirePress", "author_institution"],
        do: false,
      },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["general", "canonical"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
    },
  },
  ergo: {
    name: "Ergo",
    url: "https://www.ergophiljournal.org/e/ergo/longfeed.xml",
    color: "1",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "content:encoded", do: false },
      author: { property: "creator", do: removeNewLines },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },
    metadataConfig: {
      author: { property: ["highwirePress", "author"], do: reverseNameOrder },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
    },
  },
  studies_in_history_and_philosophy_of_science_part_a: {
    name: "Studies in History and Philosophy of Science Part A",
    url: "http://rss.sciencedirect.com/publication/science/00393681",
    color: "16",
    filter: true,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "description", do: false },
      author: { property: "creator", do: false },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },

    metadataConfig: {
      abstract: { property: ["openGraph", "description"], do: false },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["general", "canonical"], do: false },
    },
  },
  kant_yearbook: {
    name: "Kant Yearbook",
    url:
      "https://www.degruyter.com/journalissuetocrss/journals/kantyb/kantyb-overview.xml",
    color: "17",
    filter: false,
    rssOnly: false,

    rssConfig: {
      abstract: { property: "description", do: false },
      author: { property: "creator", do: false },
      date: { property: "isoDate", do: false },
      doi: { property: "prism:doi", do: false },
      endingpage: { property: "prism:endingPage", do: false },
      startingpage: { property: "prism:startingPage", do: false },
      title: { property: "title", do: false },
      volume: { property: "prism:volume", do: false },
      issue: { property: "prism:number", do: false },
      url: { property: "link", do: removeParams },
    },
    metadataConfig: {
      abstract: { property: ["openGraph", "description"], do: stripMarkUp },
      author: { property: ["highwirePress", "author"], do: false },
      date: { property: ["highwirePress", "publication_date"], do: toIso },
      doi: { property: ["highwirePress", "doi"], do: false },
      image: { property: ["openGraph", "image"], do: getImgUrl },
      firstpage: { property: ["highwirePress", "firstpage"], do: false },
      lastpage: { property: ["highwirePress", "lastpage"], do: false },
      title: { property: ["highwirePress", "title"], do: false },
      issue: { property: ["highwirePress", "issue"], do: false },
      journalTitle: { property: ["highwirePress", "journal_title"], do: false },
      url: { property: ["general", "canonical"], do: false },
      volume: { property: ["highwirePress", "volume"], do: false },
    },
  },
};

// TODO Automate Config
// const { getAndParseMetaTags } = require("./parser");
// getAndParseMetaTags(
//   "https://www.tandfonline.com/doi/full/10.1080/09608788.2019.1624946?af=R",
//   this.source.inquiry
// );
